/* Public catalog only. No API tokens. Sync IDs are store product IDs.
   image paths are local mockups in site/assets/mockups/ — not a live CDN. */
window.HABIBI_CATALOG = {
  currency: "USD",
  products: [
    { id: 462528261, slug: "ya-aini", image: "assets/mockups/ya-aini.png", name: "Ya Aini", category: "mugs", kind: "Mug", price: 18, priceLabel: "$18", spec: "11 oz · White glossy", note: "11 oz mug.", blurb: "11 oz mug.", details: [["Size", "11 oz"], ["Finish", "White glossy"], ["Material", "Ceramic"]] },
    { id: 462528274, slug: "baladi", image: "assets/mockups/baladi.png", name: "Baladi", category: "mugs", kind: "Mug", price: 18, priceLabel: "$18", spec: "11 oz · White glossy", note: "11 oz mug.", blurb: "11 oz mug.", details: [["Size", "11 oz"], ["Finish", "White glossy"], ["Material", "Ceramic"]] },
    { id: 462528282, slug: "ya-dunia", image: "assets/mockups/ya-dunia.png", name: "Ya Dunia", category: "mugs", kind: "Mug", price: 18, priceLabel: "$18", spec: "11 oz · White glossy", note: "11 oz mug.", blurb: "11 oz mug.", details: [["Size", "11 oz"], ["Finish", "White glossy"], ["Material", "Ceramic"]] },
    { id: 462528284, slug: "jiran", image: "assets/mockups/jiran.png", name: "Jiran", category: "mugs", kind: "Mug", price: 18, priceLabel: "$18", spec: "11 oz · White glossy", note: "11 oz mug.", blurb: "11 oz mug.", details: [["Size", "11 oz"], ["Finish", "White glossy"], ["Material", "Ceramic"]] },
    { id: 462532463, slug: "maamoul", image: "assets/mockups/maamoul.png", name: "Maamoul", category: "mugs", kind: "Mug", price: 18, priceLabel: "$18", spec: "11 oz · White glossy", note: "11 oz mug.", blurb: "11 oz mug.", details: [["Size", "11 oz"], ["Finish", "White glossy"], ["Material", "Ceramic"]] },
    { id: 462540373, slug: "knafeh-club", image: "assets/mockups/knafeh-club.png", name: "Knafeh Club", category: "mugs", kind: "Mug", price: 18, priceLabel: "$18", spec: "11 oz · White glossy", note: "11 oz mug.", blurb: "11 oz mug.", details: [["Size", "11 oz"], ["Finish", "White glossy"], ["Material", "Ceramic"]] },
    { id: 462532457, slug: "khalas-habibi", image: "assets/mockups/khalas-habibi.png", name: "Khalas Habibi", category: "tees", kind: "Tee", price: 32, priceLabel: "$32", spec: "Unisex S–XL", note: "Unisex tee.", blurb: "Unisex tee.", details: [["Sizes", "S, M, L, XL"], ["Fit", "Unisex"], ["Color", "Printed on a blank tee"]] },
    { id: 462540352, slug: "ya-habayeb", image: "assets/mockups/ya-habayeb.png", name: "Ya Habayeb", category: "tees", kind: "Tee", price: 32, priceLabel: "$32", spec: "Unisex S–XL", note: "Unisex tee.", blurb: "Unisex tee.", details: [["Sizes", "S, M, L, XL"], ["Fit", "Unisex"], ["Color", "Printed on a blank tee"]] },
    { id: 462532459, slug: "halawa", image: "assets/mockups/halawa.png", name: "Halawa", category: "totes", kind: "Tote", price: 34, priceLabel: "$34", spec: "Cotton · One size", note: "Cotton tote.", blurb: "Cotton tote.", details: [["Size", "One size"], ["Material", "Cotton"], ["Use", "Everyday tote"]] },
    { id: 462540360, slug: "sit-el-kul", image: "assets/mockups/sit-el-kul.png", name: "Sit El Kul", category: "totes", kind: "Tote", price: 34, priceLabel: "$34", spec: "Cotton · One size", note: "Cotton tote.", blurb: "Cotton tote.", details: [["Size", "One size"], ["Material", "Cotton"], ["Use", "Everyday tote"]] },
    { id: 462532461, slug: "ya-teta", image: "assets/mockups/ya-teta.png", name: "Ya Teta", category: "baby", kind: "Onesie", price: 28, priceLabel: "$28", spec: "3–6m · 6–12m · 12–18m", note: "Baby onesie.", blurb: "Baby onesie.", details: [["Sizes", "3–6m, 6–12m, 12–18m"], ["Color", "White"], ["Fit", "Baby onesie"]] },
    { id: 462540363, slug: "amoura", image: "assets/mockups/amoura.png", name: "Amoura", category: "baby", kind: "Onesie", price: 28, priceLabel: "$28", spec: "3–6m · 6–12m · 12–18m", note: "Baby onesie.", blurb: "Baby onesie.", details: [["Sizes", "3–6m, 6–12m, 12–18m"], ["Color", "White"], ["Fit", "Baby onesie"]] },
    { id: 462532462, slug: "beit-el-hobb", image: "assets/mockups/beit-el-hobb.png", name: "Beit El Hobb", category: "prints", kind: "Print", price: 24, priceLabel: "$24", spec: "12 × 16 in · Matte", note: "12 × 16 print.", blurb: "12 × 16 print.", details: [["Size", "12 × 16 in"], ["Paper", "Matte"], ["Frame", "Not included"]] },
    { id: 462540368, slug: "dar-el-hawa", image: "assets/mockups/dar-el-hawa.png", name: "Dar El Hawa", category: "prints", kind: "Print", price: 24, priceLabel: "$24", spec: "12 × 16 in · Matte", note: "12 × 16 print.", blurb: "12 × 16 print.", details: [["Size", "12 × 16 in"], ["Paper", "Matte"], ["Frame", "Not included"]] }
  ]
};
