window.HABIBI_PUBLIC_CONFIG = {
  CHECKOUT_ENABLED: false,
  ADSENSE_ENABLED: false,
  ADSENSE_PUBLISHER_ID: '',
  STRIPE_PUBLISHABLE_KEY: '',
  CHECKOUT_API_BASE: ''
};
window.HABIBI_CHECKOUT_ENABLED = false;
